### PR TITLE
chore: localization guide

### PR DESCRIPTION
**Pull request by jab416171**

### CODE REVIEW

**Review by EmreTech — CHANGES_REQUESTED** [review]
This guide needs more explanation. You can't just throw examples around and expect people to understand this. 
Also, this should be placed in the Interactions folder, not a new folder.

**Comment by jab416171** [comment]
> This guide needs more explanation. You can't just throw examples around and expect people to understand this. Also, this should be placed in the Interactions folder, not a new folder.

I added more to the top but please let me know if there's anything specific I should add or mention.

**Review by EmreTech — CHANGES_REQUESTED** [review]
This is better, but you should really relocate the `localization/index.mdx` file to `interactions/localization.mdx` instead of just changing the sidebar to seem that that is the case.

**Review by EmreTech — APPROVED** [review]
LGTM

**Pull request merged**
