### PR TITLE
chore: reorganize message component guides and localization guide

### PR DESCRIPTION
**Pull request by EmreTech**
This problem didn't spot my eye until after I merged #59. I should probably pay more attention next time.

FYI: the new placement of the modal guide is not final.

### CODE REVIEW

**Comment by VincentRPS** [comment]
I don’t think we need a separated category for app commands imo

**Comment by EmreTech** [comment]
I think it's reasonable. Plus, message components are in their own folder, so it wouldn't really make any sense to just leave Application Command guides in the main folder.

**Comment by VincentRPS** [comment]
> I think it's reasonable. Plus, message components are in their own folder, so it wouldn't really make any sense to just leave Application Command guides in the main folder.

But message components and app commands are nothing alike

**Comment by EmreTech** [comment]
> > I think it's reasonable. Plus, message components are in their own folder, so it wouldn't really make any sense to just leave Application Command guides in the main folder.
> 
> 
> 
> But message components and app commands are nothing alike

Ummmmm... what does that have to do with this discussion? I'm trying to say since Message Components have their own folder (and you aren't complaining), why not give Application Commands their own folder?

**Review by BobDotCom — APPROVED** [review]

**Pull request merged**
