### PR TITLE
feat: replit installation

### PR DESCRIPTION
**Pull request by JustaSqu1d**

### CODE REVIEW

**Comment by Lulalaby** [comment]
Didn't we say no replit..

**Comment by JustaSqu1d** [comment]
> Didn't we say no replit..

Yes, but Replit seems like a great alternative to try a new framework without installing things. Replit is also a staple for Chromebook users that do not have access to Linux. What we did say no to was Replit for hosting.

**Comment by VincentRPS** [comment]
I personally would say no to this PR, but I'd have to let @BobDotCom decide whether to merge or not (also ref: https://discord.com/channels/881207955029110855/955489320108687380/1071571498604711967)

**Comment by Lulalaby** [comment]
I'm honestly also against it. Closing it for now. Bob can reopen it if he thinks it's worth it.

**Pull request closed without merging**
